language: objective-c
before_install:
  - sudo chown -R travis ~/Library/RubyMotion
  - mkdir -p ~/Library/RubyMotion/build
  - sudo motion update
env: SPEC_SKIP_NETWORKING=1 LANG=en_US.UTF-8
script:
  - bundle exec rake pod:install --silent
  - bundle exec rake spec
